# Generated by Django 4.2.2 on 2023-06-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='etiqueta',
            field=models.CharField(choices=[('Trabajo', 'Trabajo'), ('Personal', 'Personal'), ('Estudio', 'Estudio')], null=True),
        ),
    ]
