# Generated by Django 4.2.2 on 2023-06-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_tarea_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_completada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
