# Generated by Django 4.2.2 on 2023-07-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_tarea_fecha_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='observacion',
            field=models.TextField(null=True),
        ),
    ]
